<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUTRJTkz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUTRJTkz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUTRJTkz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUTRJTkz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUTRJTkz\App_KernelDevDebugContainer([
    'container.build_hash' => 'UTRJTkz',
    'container.build_id' => '51412374',
    'container.build_time' => 1619212464,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUTRJTkz');
