<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWkeTI5j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWkeTI5j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWkeTI5j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWkeTI5j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWkeTI5j\App_KernelDevDebugContainer([
    'container.build_hash' => 'WkeTI5j',
    'container.build_id' => '6b1d4f88',
    'container.build_time' => 1619194399,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWkeTI5j');
